import type { AppProps } from 'next/app';
import Head from 'next/head';
import Script from 'next/script';
import { NextPage } from 'next';
import { PropsWithChildren, ReactElement } from 'react';
import { CookiesProvider } from 'react-cookie';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';

import { FONTS } from '@constants';
import { injectGlobalStyles } from '@styles/globalStyles';
import { elasticApmScript } from '@lib/thirdparty/elasticApm';
import { AppWrapper } from '@modules/app-wrapper/scripts/contexts/app-wrapper.context';
import { CustomerWrapper } from '@modules/app-wrapper/scripts/contexts/customer.context';
import { BasketWrapper } from '@modules/app-wrapper/scripts/contexts/basket.context';
import { UIWrapper } from '@modules/app-wrapper/scripts/contexts/ui.context';
import DefaultLayout from '@modules/app-wrapper/layouts/Default.layout';
import { TranslationsWrapper } from '@modules/app-wrapper/scripts/contexts/translations.context';

export type TPage<P = PropsWithChildren, IP = P> = NextPage<P, IP> & {
  Layout?: (props: P) => ReactElement;
};

type TCustomAppProps = AppProps & {
  Component: TPage;
};

const queryClient = new QueryClient();

function App({ Component, pageProps }: TCustomAppProps) {
  const STRINGIFIED_GLOBAL_STYLES = injectGlobalStyles();
  const Layout = Component.Layout || DefaultLayout;

  return (
    <>
      <CookiesProvider>
        <QueryClientProvider client={queryClient}>
          <AppWrapper>
            <TranslationsWrapper translations={pageProps?.translations}>
              <CustomerWrapper>
                <BasketWrapper>
                  <UIWrapper>
                    <Layout page={pageProps?.page}>
                      <Head>
                        <title>Create Next App</title>
                        <meta
                          name="description"
                          content="Generated by create next app"
                        />
                        <meta
                          name="viewport"
                          content="width=device-width, initial-scale=1"
                        />
                        <link rel="icon" href="/favicon.ico" />
                        <style dangerouslySetInnerHTML={{ __html: FONTS }} />
                        <style
                          dangerouslySetInnerHTML={{
                            __html: STRINGIFIED_GLOBAL_STYLES,
                          }}
                        />
                      </Head>
                      <Component {...pageProps} />
                    </Layout>
                  </UIWrapper>
                </BasketWrapper>
              </CustomerWrapper>
            </TranslationsWrapper>
          </AppWrapper>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
        <Script {...elasticApmScript} />
      </CookiesProvider>
    </>
  );
}

export default App;
