// IMPORTANT: THIS FILE SHOULD NEVER BE LOAD IN ANY BROWSER RELATED FILE
// SECURITY RISK
const appConfig: TAppConfig = {
  APP: {
    ORIGIN: process.env.APP_ORIGIN,
    APP_HEALTH_CLIENT_ID: process.env.APP_HEALTH_CLIENT_ID,
    APP_SFCC_REQUEST_CLIENT_ID: process.env.APP_SFCC_REQUEST_CLIENT_ID,
    APP_INTERNAL_REQUEST_TOKEN: process.env.APP_INTERNAL_REQUEST_TOKEN,
    APP_WEBHOOK_BUSTER_CLIENT_ID: process.env.APP_WEBHOOK_BUSTER_CLIENT_ID,
  },
};

export { appConfig };
