describe('Home page index entry', () => {
  beforeEach(() => {
    cy.visit('/');
  });

  it('displays the correct title', () => {
    cy.title().should('include', 'Create Next App');
  });

  it('displays the correct description', () => {
    cy.get('meta[name="description"]').should(
      'have.attr',
      'content',
      'Generated by create next app'
    );
  });

  it('displays the correct paragraph', () => {
    cy.get('p').contains('Get started by editing');
  });
});

export {};
